const paragraphs = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id mauris in magna rhoncus faucibus egestas non orci. Donec risus libero, placerat ut porta id, bibendum at lorem. Donec sollicitudin tincidunt posuere. Fusce sed euismod sapien. Nullam accumsan, ante nec tincidunt vestibulum, dui purus blandit nulla, non pharetra massa felis eget massa. Nulla in ipsum id sem aliquam feugiat congue sit amet nulla. Nam ante erat, dignissim id fermentum in, porttitor ut metus. Nullam a volutpat magna. Vivamus suscipit cursus tristique. Integer interdum aliquet ex nec consequat. Vestibulum eu pretium diam. Mauris vel felis ut quam molestie fermentum vel sit amet ligula. Nulla accumsan metus sed ipsum pharetra, et mollis nibh luctus. Etiam facilisis, sapien non tempor interdum, dolor justo cursus quam, sed laoreet quam magna at nunc. Phasellus eget porta metus.",
  "Morbi non ultricies neque. Nulla facilisi. Sed condimentum dui at vestibulum feugiat. Vestibulum a eros quis justo efficitur tempus. Integer volutpat eu ex nec congue. Nam eu justo eget nunc lacinia blandit a vel elit. Duis dignissim, metus ac feugiat fringilla, risus nisi sollicitudin sapien, vel congue augue est vel quam. Maecenas eget ultricies velit. Etiam dapibus cursus nulla, eget tincidunt tortor commodo vel.",
  "In hac habitasse platea dictumst. Vivamus auctor, odio vel tincidunt imperdiet, arcu orci volutpat tellus, nec dapibus nulla leo nec turpis. Quisque cursus, justo id ultrices vestibulum, lacus ex accumsan ligula, et interdum libero neque nec ligula. Pellentesque nec augue id urna viverra vulputate. Sed aliquam ut leo eu tincidunt. Proin tincidunt, eros vitae tincidunt vulputate, nunc elit vulputate nunc, nec posuere dui velit eget enim. Integer feugiat velit eu mauris euismod aliquet. Sed ac leo euismod, tincidunt metus vel, dapibus tortor.",
  "Nam nec massa vel nunc ullamcorper pharetra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam id convallis nulla. Curabitur nec nisl velit. Suspendisse potenti. Maecenas dictum urna eu ullamcorper fringilla. Duis a urna non dolor tristique condimentum. Fusce sed quam at ligula vestibulum gravida nec quis nisi. Sed euismod tortor ac ex aliquam facilisis.",
  "Ut accumsan fringilla nulla, sit amet accumsan nulla dictum quis. Morbi suscipit convallis justo id tincidunt. Vestibulum vitae libero ac quam sodales laoreet a ut felis. Curabitur ut dolor a risus pellentesque euismod. Suspendisse potenti. Sed auctor augue a ultricies vehicula. Duis nec diam nec velit fermentum pellentesque vel eget turpis. Nullam sed nulla nec ligula dapibus vulputate. Sed ut nisl a ante tincidunt dapibus a quis orci.",
  "Nunc vel fermentum orci. Integer nec vehicula libero. Fusce eleifend sem eu felis mattis, nec luctus nisi pellentesque. Suspendisse eu nisi nec urna suscipit imperdiet. Sed imperdiet erat vel ante posuere, vel vulputate arcu bibendum. Morbi vitae ultricies mauris. Nullam ut elit vel augue aliquet aliquet. Fusce interdum quam vel elit varius, vel vestibulum justo dapibus. Etiam ac mi a nisl cursus ullamcorper.",
  "Quisque sit amet ligula vitae tellus dictum mattis. Aenean sit amet arcu sed arcu fermentum rhoncus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam auctor nisi a orci fringilla, at laoreet nisl hendrerit. Maecenas eu lacus in velit facilisis ullamcorper eu id quam. Suspendisse potenti. Integer vitae efficitur sem, ut mattis velit. Suspendisse potenti. Sed non leo a orci tincidunt dignissim ac eu odio.",
  "Praesent eu ligula in elit ullamcorper ultrices. Sed eu scelerisque libero. Sed ac malesuada felis, nec tincidunt nisl. Aliquam nec mi nec lectus aliquet ultrices. Ut nec ligula vel turpis volutpat suscipit. Sed ut purus non ex eleifend mattis. Nullam fringilla, sapien et cursus hendrerit, risus quam accumsan quam, nec ultricies justo elit nec justo. Curabitur vestibulum, ligula in pulvinar aliquet, sem justo volutpat nunc, vitae pharetra libero dui eget enim.",
  "Integer fermentum risus quis quam efficitur, ac feugiat urna tincidunt. Fusce efficitur ipsum nec nisl fringilla, ac vulputate libero dapibus. Sed bibendum dolor id nunc ultrices, vitae consectetur metus fermentum. Aliquam tristique, felis nec vehicula scelerisque, orci purus interdum lectus, ut commodo lacus arcu nec turpis. Curabitur nec turpis eu libero cursus vulputate. Vivamus nec justo eget sapien condimentum efficitur a a massa. Sed nec justo ligula. In hac habitasse platea dictumst.",
  "Pellentesque ac nibh vitae elit suscipit semper eu vel libero. Proin aliquam odio eget nulla posuere vulputate. Vivamus nec neque a neque laoreet varius id id libero. Aenean hendrerit urna et malesuada tincidunt. Nulla facilisi. Ut tristique odio eu nunc rhoncus feugiat. Integer at feugiat nisi. Suspendisse potenti. Suspendisse potenti. In hac habitasse platea dictumst.",
  "Maecenas tristique, turpis sit amet dictum fermentum, arcu erat vulputate lacus, vel dapibus elit massa a mi. Fusce vehicula auctor dui, eget luctus elit commodo vel. Sed eu efficitur nulla. Morbi a odio a quam auctor aliquet eu a odio. Duis in quam nec nisi posuere varius. Aliquam erat volutpat. Morbi commodo, lectus ut feugiat vulputate, lectus dolor efficitur neque, ut sodales augue ipsum id augue. Sed convallis a velit vel pellentesque. Etiam venenatis lectus vel erat facilisis, ac dignissim sapien scelerisque. Vivamus suscipit lacus vitae ligula cursus, in facilisis metus congue. Integer euismod purus vitae vestibulum auctor."
];